#! /bin/sh
cd "$(dirname "$0")"/.. || exit 1

OCAML=ocaml
MINCAMLC=ocaml/mincamlc
ASML_RUNNER=tools/asml

nb_cases=0
nb_failures=0

echo "--------------------"
for test_case in tests/asml/*.ml
do
    nb_cases=$((nb_cases + 1))
    echo "testing asml structure generated by: $test_case"

    $MINCAMLC -asml "$test_case" 2> /dev/null 1> /dev/null
    if [ "$?" != "0" ]
    then
        nb_failures=$((nb_failures + 1))
        echo "KO ~~~~~~~~~~ compilation failed"
        continue
    fi

    out=`$ASML_RUNNER ./a.out 2> /dev/null`
    if [ "$?" != "0" ]
    then
        nb_failures=$((nb_failures + 1))
        echo "KO ~~~~~~~~~~ not valid asml code"
        rm a.out
        continue
    fi

    expected=`$OCAML $test_case 2> /dev/null`
    if [ "$out" != "$expected" ]
    then
        nb_failures=$((nb_failures + 1))
        echo "KO ~~~~~~~~~~ output not as expected\n---actual---\n$out\n---expected---\n$expected\n"
    else
        echo "OK"
    fi
    rm a.out
done

echo "run $nb_cases tests"
if test $nb_failures -gt $((0))
then
    echo "$nb_failures/$nb_cases tests failed!"
else
    echo "all passed!"
fi
